### ISSUE TITLE
find a way to automatically run the drift correction in Thunderstorm

### ISSUE THREAD

**Issue by chzchz** [oeway/sagenb#11]

**Comment by oeway** [comment]
I didn't include this because after drift correction, I need to define the output image size according to different dataset during rendering.

I have submit a open issue on the thunderSTORM website : https://code.google.com/p/thunder-storm/issues/detail?id=23

**Comment by oeway** [comment]
Drift correction is now the default option (with version number >28),  the default correction method is done by the following macro:

```
run("Show results table", "action=drift magnification=5.0 save=false showcorrelations=false method=[Cross correlation] steps=5");
```

So, it's using Cross correlation.

**Please note that, the particle table which you can download is the original result without correction, the default drift correction is only applied to the output image(tif and png).**
