### ISSUE TITLE
Data load can not start in more than 10 minutes

### ISSUE THREAD

**Issue by aaristov** [oeway/sagenb#12]
InputData:
/pasteur/projets/Imod-grenier/Mickael/A amalyser/240215_Rahaf_Stephanie_SKOV3_latruculin/exp_3/
/tmp/tmpr7WZFB
Running in directory: /pasteur/projets/Imod-grenier/Will/bin/ImageJ.app
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be
created.
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
192.168.0.50 8888
running macro file
ImageJ 1.49m; Java 1.7.0_65 [64-bit]; 423 commands; 0 macros    

log:
==>loading data...

**Comment by aaristov** [comment]
You could add the timestamps at the beginning of the log lines.

**Comment by oeway** [comment]
Hi,
Thanks for this suggestion, I think it's because the data file is large, and for your case, your a big folder with 30000 files, it takes a long time to sort and load these files. If possible, save in a single multi-page tiff file would increase the speed a lot.
I just checked the your worksheet, it's running well.

You are right, maybe it's helpful to add a timestamp.

**Comment by oeway** [comment]
Hi Andrey,

I have updated a new version(>28) of thunderSTORM analysis worksheet which has the timestamp, check it out.

And you can use virtual stack for processing, as in my test, it seems faster. If you want try, run with a newer version (>31), if you can choose use or not virtual mode by setting virtualMode = true;  or virtualMode = false; in the macro. You can find where to modify by searching in the worksheet.
